# ==================================================
# Codecov configuration
# Docs: https://docs.codecov.com/docs/codecov-yaml
# ==================================================

codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

# --------------------------------------------------
# Pull Request comment behavior
# --------------------------------------------------
comment:
  layout: "header, diff, changes, footer"
  behavior: default
  require_changes: true
  max_comments: 1
  show_results: changed
  emoji: true

comment_header: |
  📊 **Codecov Coverage Report**
  Hello @{{author}} 👋
  Here is the coverage summary for this PR.

comment_footer: |
  🚀 Thanks for keeping the code quality high!
  Full report: [{{build_url}}]

# --------------------------------------------------
# Coverage configuration
# --------------------------------------------------
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        informational: false

    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

# --------------------------------------------------
# Ignore paths from coverage
# --------------------------------------------------
ignore:
  - "docs/**"
  - "scripts/**"
  - "ci/**"
  - "**/*.md"

# --------------------------------------------------
# Flags (explicit, even if single-project)
# This is one of the things that helps
# Codecov mark YAML as "Configured"
# --------------------------------------------------
flags:
  core:
    carryforward: false

# --------------------------------------------------
# Disable default GitHub Checks annotations
# (explicit override = non-default behavior)
# --------------------------------------------------
github_checks:
  annotations: false
