name: 🐞 Bug Report
description: Laporkan bug atau error di Termux App Store dengan lengkap.
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Terima kasih sudah melaporkan bug!
        Silakan isi semua field di bawah agar tim bisa menindaklanjuti dengan cepat.

  - type: input
    id: description
    attributes:
      label: Deskripsi Bug
      placeholder: Misal: Termux App Store crash saat memilih paket tertentu
    validations:
      required: true

  - type: input
    id: package_feature
    attributes:
      label: Paket / Fitur Terkait
      placeholder: Misal: Instalasi paket, pencarian, panel list, dll.
    validations:
      required: true

  - type: dropdown
    id: termux_version
    attributes:
      label: Termux Version
      options:
        - "0.144"
        - "0.145"
        - "Lainnya"
    validations:
      required: true

  - type: input
    id: android_version
    attributes:
      label: Android Version
      placeholder: Misal: 12
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Device Architecture
      options:
        - aarch64
        - armv7l
        - x86_64
        - Lainnya
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: Termux App Store Version
      placeholder: Misal: 1.0.5
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Langkah Reproduksi
      placeholder: |
        1. Buka Termux App Store
        2. Pilih paket "abc"
        3. Klik Install / Update
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Hasil yang Diharapkan
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log / Screenshot

  - type: textarea
    id: additional_context
    attributes:
      label: Konteks Tambahan
